---
# docker compose to startup a development database

version: '3.1'

services:
  db:
    image: postgres
    restart: always
    container_name: postgres
    environment:
      PUID: 1000
      PGID: 1000
    env_file:
      - ./.env
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - '6500:5432'

  # pgAdmin:
  #   image: dpage/pgadmin4
  #   container_name: pgAdmin
  #   env_file:
  #     - ./.env
  #   ports:
  #     - '5050:80'
